# image,docs: https://github.com/HeyPuter/puter

services:

  puter:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    restart: unless-stopped
    ports:
      - $W9_HTTP_PORT_SET:4100
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - puter_config:/etc/puter
      - puter_data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  puter_config:
  puter_data:
    
networks:
  default:
    name: $W9_NETWORK
    external: true
