# image: https://hub.docker.com/r/fluent/fluent-bit
# docs: https://docs.fluentbit.io/manual


services:
  fluent-bit:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    env_file: .env
    ports:
      - ${W9_HTTP_PORT_SET}:24224
    volumes:
      - ./src/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - logs:/var/log/fluentbit
    restart: unless-stopped

volumes:
  logs:

networks:
  default:
    name: $W9_NETWORK
    external: true