# image: https://hub.docker.com/r/vaultwarden/server
# docs: https://github.com/dani-garcia/vaultwarden/wiki

version: '3.8'
services:
  vaultwarden:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    restart: unless-stopped
    ports:
      - $W9_HTTP_PORT_SET:80
    env_file: .env
    volumes:
      - "vaultwarden_vol:/data/"
  mariadb:
    image: mariadb:$W9_DB_VERSION
    container_name: "$W9_ID-mariadb"
    hostname: "mariadb"
    restart: always
    env_file:
      - .env
    volumes:
      - "mariadb_vol:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "MYSQL_ROOT_PASSWORD=$W9_POWER_PASSWORD"
      - "MYSQL_PASSWORD=$W9_RCODE"
      - "MYSQL_DATABASE=vaultwarden"
      - "MYSQL_USER=vaultwarden"
volumes:
  vaultwarden_vol:
  mariadb_vol:
    
networks:
  default:
    name: $W9_NETWORK
    external: true
