# image: https://hub.docker.com/r/espocrm/espocrm
# dockfile: https://github.com/espocrm/espocrm-docker
# docs: https://docs.espocrm.com/administration/installation-by-script/

version: '3.8'

services:

  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  espocrm:
    image: espocrm/espocrm
    container_name: ${APP_NAME}
    env_file: .env
    environment:
      ESPOCRM_DATABASE_HOST: ${APP_NAME}-db
      ESPOCRM_DATABASE_USER: ${APP_DB_MYSQL_USER}
      ESPOCRM_DATABASE_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      ESPOCRM_ADMIN_USERNAME: ${APP_USER}
      ESPOCRM_ADMIN_PASSWORD: ${APP_PASSWORD}
      ESPOCRM_SITE_URL: "http://localhost:${APP_HTTP_PORT}"
    volumes:
      - espocrm:/var/www/html
    restart: unless-stopped
    ports:
      - ${APP_HTTP_PORT}:80

  espocrm-daemon:
    image: espocrm/espocrm
    container_name: ${APP_NAME}-daemon
    volumes:
      - espocrm:/var/www/html
    restart: unless-stopped
    entrypoint: docker-daemon.sh

  espocrm-websocket:
    image: espocrm/espocrm
    container_name: ${APP_NAME}-websocket    
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:${APP_WEBSOCKET_PORT}"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - espocrm:/var/www/html
    restart: unless-stopped
    entrypoint: docker-websocket.sh
    ports:
      - ${APP_WEBSOCKET_PORT}:8080
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true
      
volumes:
  mysql:
  espocrm:
