# image: https://hub.docker.com/r/easysoft/zentao
# docs: https://github.com/easysoft/zentaopms

version: '3.8'

services:
  zentao:
    image: easysoft/zentao:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - zentao:/www/zentaopms
    environment:
      # The belows vars is need, otherwise container error
      zentao_DB_HOST: ${DB_MYSQL_HOST}
      zentao_DB_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DB: ${DB_MYSQL_NAME}
      MYSQL_HOST: ${DB_MYSQL_HOST}  
    links: 
      - mysql
    restart: unless-stopped
    entrypoint: bash -c "cat /my_cmd > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd
      
  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    #ports:
    # - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  zentao:
  mysql_data:

configs:
  my_cmd:
    file: ./cmd.sh
