# image,docs: https://databasus.com/installation

services:
  databasus:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    env_file: .env
    ports:
      - "$W9_HTTP_PORT_SET:4005"
    volumes:
      - databasus-data:/databasus-data
    restart: unless-stopped

volumes:
  databasus-data:
    
networks:
  default:
    name: $W9_NETWORK
    external: true
