
# image: https://hub.docker.com/r/percona/pmm-server

version: '3.8'

services:
  pmmserver:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    ports:
      - $W9_HTTPS_PORT_SET:443
    env_file: .env
    volumes:
      - pmm-data:/srv
    restart: unless-stopped

volumes:
  pmm-data:

networks:
  default:
    name: $W9_NETWORK
    external: true
  