# image: https://hub.docker.com/r/getmeili/meilisearch
# docs: https://www.meilisearch.com/docs

services:
  meilisearch:
    image: getmeili/meilisearch:${W9_VERSION}
    container_name: $W9_ID
    restart: unless-stopped
    ports:
      - ${W9_HTTP_PORT_SET}:7700
    env_file: .env
    environment:
      - MEILI_ENV=${MEILI_ENV}
    volumes:
      - meilisearch_data:/meili_data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

volumes:
  meilisearch_data:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
