# image: ccr.ccs.tencentyun.com/discuzq/dzq
# docs: https://discuz.com/docs/Linux%20%E4%B8%BB%E6%9C%BA.html#%E5%9F%BA%E4%BA%8E-docker-%E5%AE%B9%E5%99%A8-%E6%8E%A8%E8%8D%90

version: '3.8'

services:
  discuzq:
    image: websoft9dev/discuzq:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - discuzq:/var/www/discuz
    restart: unless-stopped
    environment:
      DISCUZQ_MYSQL_DATABASE: ${DB_MYSQL_NAME}
      DISCUZQ_MYSQL_USER: ${DB_MYSQL_USER}
      DISCUZQ_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DISCUZQ_MYSQL_HOST: db
      DISCUZQ_SITENAME: ${APP_SITENAME}
    depends_on:
      - db
     
  db:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    hostname: db
    restart: unless-stopped
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

volumes:
  discuzq:
  mysql:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
