# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm

version: '3.8'

services:
  suitecrm:
    image: docker.io/bitnami/suitecrm:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_HTTP_PORT}:8080'
    env_file: .env
    environment:
      - SUITECRM_DATABASE_HOST=${APP_NAME}-db 
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=${APP_DB_MYSQL_USER}
      - SUITECRM_DATABASE_NAME=${APP_DB_MYSQL_NAME}
      - SUITECRM_DATABASE_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - SUITECRM_USERNAME=${APP_USER}
      - SUITECRM_PASSWORD=${APP_PASSWORD}
    volumes:
      - suitecrm:/bitnami/suitecrm
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:${APP_DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db 
    environment:
      - MARIADB_ROOT_PASSWORD=${APP_DB_MYSQL_PASSWORD}
      - MARIADB_DATABASE=${APP_DB_MYSQL_NAME}
      - MARIADB_USER=${APP_DB_MYSQL_USER}
      - MARIADB_PASSWORD=${APP_DB_MYSQL_PASSWORD}
    ports:
      - '${APP_DB_MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql_data:
  suitecrm: 
